# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id号')),
                ('username', models.CharField(max_length=20, verbose_name='用户名称')),
                ('nickname', models.CharField(max_length=50, verbose_name='用户昵称')),
                ('password', models.CharField(max_length=60, verbose_name='用户密码')),
                ('age', models.IntegerField(default=18, verbose_name='用户年龄')),
                ('gender', models.BooleanField(default=0, verbose_name='性别')),
                ('born', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('email', models.EmailField(max_length=255, verbose_name='用户邮箱')),
            ],
        ),
    ]
