# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 08:06
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='user',
            name='header',
            field=models.ImageField(default='static/images/1.jpg', upload_to='static/images/headers/', verbose_name='用户头像'),
        ),
    ]
